TRUTH = (
    "Pernah gak nyuri uang nyokap atau bokap? Alesanya?",
    "Pernah cinta bertepuk sebelah tangan? kalo pernah sama siapa? rasanya gimana brou?",
    "Pernah gak dilabrak kakak kelas?",
    "(bgi yg muslim) pernah ga solat seharian?",
    "Pengalaman berharga yang ga pernah dilupakan apa?"
    "Tipe pasangan yang kamu mau itu gimana?",
    "Mantan paling awet?",
    "Kapan pertama pacaran.siapa.dan knapa bisa pacaran?",
    "Yang paling pendek menurut kamu tapi imut siapa?",
    "Orang yang paling kamu benci,tapi kamu gabisa gak temenan sama dia siapa?alasan nya?",
    "Sahabat lawan jenis yang menurut kamu bakalan cocok kalo jadi pacar kamu siapa?",
    "Kamu pernah gak masturbasi?",
    "Apakah kamu telah membuat hantu seseorang??"
    "Pernahkah kamu masuk pada orang tua kamu melakukan 'itu'?",
    "Siapa orang terakhir yang paling kamu sukai? Mengapa?",
    "Apakah kamu pernah diskors dari sekolah??",
    "Jika kamu harus memilih antara telanjang atau pikiran kamu muncul dalam gelembung pikiran di atas kepala kamu untuk dibaca semua orang, mana yang akan kamu pilih?",
    "Apa satu hal yang kamu takut kehilangan?",
    "Apakah kamu menyukai seseorang saat ini?",
    "Satu hal tentang sahabatmu yang membuatmu cemburu?",
    "Apakah kamu akan menipu pacarmu untuk pria kaya?",
    "Apa giliran terbesarmu?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Jelaskan pasangan ideal kamu.",
    "Apa hal paling menakutkan yang pernah kamu lakukan?",
    "Apakah kamu pernah mengupil dan memakannya?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Apakah kamu pernah berbohong tentang usia kamu untuk berpartisipasi dalam kontes?",
    "Apakah kamu pernah ketahuan sedang memeriksa seseorang?",
    "Kamu pernah boong sama pacarmu? Kalo pernah terakhir boong apa.",
  
)

DARE = (
    "Tampilkan foto paling memalukan di ponsel kamu"
    "Tampilkan lima orang terakhir yang kamu kirimi SMS dan apa isi pesannya",
    "Biarkan seluruh grup DM seseorang dari akun Instagram kamu",
    "Makan bawang putih mentah",
    "Lakukan 100 squat",
    "Simpan tiga es batu di mulutmu sampai meleleh",
    "Katakan sesuatu yang kotor kepada orang di sebelah kirimu. Kamu punya teman!",
    "Berikan pijatan kaki pada orang di sebelah kanan kamu",
    "Masukkan 10 cairan berbeda yang tersedia ke dalam cangkir dan minumlah",
    "* Ucapkan kata pertama yang muncul di pikiranmu",
    "Berikan lap dance kepada seseorang pilihan kamu",
    "Lepaskan empat potong pakaian",
    "Suka 15 posting pertama di umpan berita Facebook kamu",
    "Makan sesendok mustard",
    "Pejamkan matamu sampai kamu pergi lagi",
    "Kirim sext ke orang terakhir di buku telepon kamu",
    "Pamerkan wajah orgasme kamu",
    "Makan pisang dengan menggoda",
    "Kosongkan dompet / dompet kamu dan tunjukkan kepada semua orang apa yang ada di dalamnya",
    "Lakukan perayapan seksi terbaikmu",
    "Berpura-puralah menjadi orang di sebelah kananmu selama 10 menit",
    "Makan camilan tanpa menggunakan tangan",
    "Katakan dua hal jujur ​​tentang semua orang dalam grup",
    "Twerk sebentar",
    "Cobalah membuat grup tertawa secepat mungkin",
    "Cobalah untuk memasukkan seluruh kepalan tanganmu ke dalam mulutmu",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu",
    "Coba jilat sikumu",
    "Posting selfie tertua di ponsel kamu di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "Melolong seperti serigala selama dua menit",
    "Menari tanpa musik selama dua menit",
    "Tari tiang dengan tiang imajiner",
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan makanan ringan ke dalam mulut kamu sekaligus sebanyak yang kamu bisa",
    "Kirim selfie terbaru kamu.",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian facebook kamu",
    "Kirim tangkapan layar galeri kamu.",
    "Kirim tangkapan layar kotak masuk messenger kamu",
    "Katakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar kotak masuk twitter kamu",
    "Kirim tangkapan layar layar berkamu kamu.",
    "Kirim cover lagu favoritmu. ",
    "Lakukan lelucon lirik pada seseorang dan kirimkan buktinya.",
    "Akui gebetanmu saat ini. ❤️",
    "Nyatakan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri kamu.",
    "Jadikan gambar gebetanmu sebagai dpmu.",
    "Kirim foto sexi kamu.",
)